### ISSUE TITLE
View error on 2.5.1

### ISSUE THREAD

**Issue by gpinkham** [mcl-de/redmine_change_issue_author#3]
Not sure if there are any special install instructions with this one..   I git cloned it into the plugins directory..    restarted passenger and received a 500 when trying to view an issue..  error from logs:

```
Started GET "/issues/1084" for ******* at 2014-07-16 10:45:14 -0400
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"1084"}
  Current user: gpinkham (id=3)
  Rendered issues/_action_menu.html.erb (3.2ms)
  Rendered plugins/redmine_issue_checklist/app/views/issues/_checklist.html.erb (2.1ms)
  Rendered issue_relations/_form.html.erb (1.7ms)
  Rendered issues/_relations.html.erb (7.8ms)
  Rendered issues/_history.html.erb (121.6ms)
  Rendered issues/_action_menu.html.erb (3.6ms)
  Rendered plugins/redmine_change_issue_author/app/views/issues/_attributes.html.erb (2.9ms)
  Rendered issues/_form.html.erb (17.7ms)
  Rendered issues/_edit.html.erb (18.7ms)
  Rendered plugins/event_notifications/app/views/issues/show.html.erb within layouts/base (186.8ms)
Completed 500 Internal Server Error in 243.8ms

ActionView::Template::Error (':parent' is not an ActiveModel-compatible object that returns a valid partial path.):
    1: <% html = Nokogiri::HTML.fragment(render(:parent)) %>
    2: <% html.at_css("div.splitcontentleft").first_element_child().before(capture do %>
    3: 
    4: <% if User.current.allowed_to?(:edit_issue_author, @project) %>
  app/views/issues/_form.html.erb:41:in `block in _app_views_issues__form_html_erb___2267370733398219273_70242283972800'
  app/helpers/application_helper.rb:1049:in `labelled_fields_for'
  app/views/issues/_form.html.erb:1:in `_app_views_issues__form_html_erb___2267370733398219273_70242283972800'
  app/views/issues/_edit.html.erb:8:in `block in _app_views_issues__edit_html_erb__711111788133632355_70242283847060'
  app/helpers/application_helper.rb:1042:in `labelled_form_for'
  app/views/issues/_edit.html.erb:1:in `_app_views_issues__edit_html_erb__711111788133632355_70242283847060'
  app/controllers/issues_controller.rb:128:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:125:in `show'
```

**Comment by Fank** [comment]
Should be fixed with 0.0.2
